### PR TITLE
Public continuous integration using Travis CI

### PR DESCRIPTION
**Pull request by p-jackson**
From the commit history it sounds like there's a secret Jenkins server somewhere that runs the build. But dRunner's a public repo right, so why not have public CI?

The CI currently only checks whether the build is successful, doesn't run the unit tests.

1. I couldn't figure out how to run the tests
2. Looks like the tests always return `0` anyway, so Travis can't know when they've failed

But checking the compile is still useful, especially since it'll automatically check all pull requests.

You can see an example of it working (including a successful build badge at the top of the readme) in this repo: https://github.com/p-jackson/drunner

### CODE REVIEW

**Comment by j842** [comment]
Very nice, thank you!

**Comment by p-jackson** [comment]
If you do want to merge the pull request you'll also need to flick a switch in Travis first. That's as simple as:

1. Logging in here https://travis-ci.org/profile and doing the oauth thing
2. Flicking the switch beside the `drunner/drunner` repo.

**Comment by p-jackson** [comment]
Or you could just elevate my member permissions to allow me to grant oauth to the organisation repos ;)

**Comment by p-jackson** [comment]
## Wooo! Look at it go!

**Pull request merged**
